### ISSUE TITLE
Wi-Fi issue

### ISSUE THREAD

**Issue by bujnan** [gabrielcasag/EFI-IDEAPAD-i5-8250U-330-15IKB-OPENCORE#1]
Hello my friend, thank you for sharing the files, the installation was successful, but the Wi-Fi doesn't work? 
As you can see in the Image below. I can't turn it On & Off.
AirDrop is working, the Wi-fi not!
My laptop is the same as yours.
can you help me please
Can you tell me what is the BIOS configuration you have?
![IMG_20221007_010045](https://user-images.githubusercontent.com/71279722/194434034-170efb25-c8c5-4816-abe8-11b7d78ba53d.jpg)

**Comment by gabrielcasag** [comment]
hey @bervill25

can you specify what is your wi-fi card and which version of MacOs u are running?

i'm using [AirportItlwm](https://openintelwireless.github.io/itlwm/Installation.html#airportitlwm) which has a kext for each macOS version, and my EFI is setup to Monterey.

[here] (https://openintelwireless.github.io/) u can find more information also about the intel wifi cards support

about the BIOS config i just updated the Readme with that info

**Comment by bervill25** [comment]
> hey @bervill25
> 
> can you specify what is your wi-fi card and which version of MacOs u are running?
> 
> i'm using [AirportItlwm](https://openintelwireless.github.io/itlwm/Installation.html#airportitlwm) which has a kext for each macOS version, and my EFI is setup to Monterey.
> 
> [here] (https://openintelwireless.github.io/) u can find more information also about the intel wifi cards support
> 
> about the BIOS config i just updated the Readme with that info
Thank you so much for reply my friend.
I'm also using Monterey Version.
My wi-fi card is: 
Qualcomm Atheros QCA9377 Wireless Network Adapter

**Comment by bujnan** [comment]
Thank you so much for reply my friend.
I'm also using Monterey Version.
My wi-fi card is:
Qualcomm Atheros QCA9377 Wireless Network Adapter
Which kext do I have to use?

**Comment by gabrielcasag** [comment]
your wi-fi card seems to be incompatible as i saw [here](https://www.olarila.com/topic/12584-kext-for-qualcomm-atheros-nfa435qca9377-on-big-sur/)

i suggest you to upgrade your wifi card for a native one like the broadcoms (bcm94360ng is a example)

more info about in theses links:
https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/
https://dortania.github.io/Wireless-Buyers-Guide/
