### ISSUE TITLE
Trackpad not working in hackintosh Monterrey Lenovo ideap 330s 15IKB

### ISSUE THREAD

**Issue by Frgaro** [gabrielcasag/EFI-IDEAPAD-i5-8250U-330-15IKB-OPENCORE#15]
Thank you very much for this interesting contribution. I have a Lenovo Ideapap 330s 15IKB and I have built a hackintosh with Monterrey following your instructions. Everything works fine except the trackpad. Any suggestions?

Thanks a lot

**Comment by gabrielcasag** [comment]
hey @Frgaro

are u identified your trackpad type?
I made this EFI based on my hardware and my trackpad are the ELAN ones

If u have synaptics, I think that changing the voodoi2celan by the voodooi2csynaptics in the kext folder and adjust the .plist its enough

more info: https://github.com/VoodooI2C/VoodooI2C
and
https://dortania.github.io/Getting-Started-With-ACPI/Laptops/trackpad.html
