### ISSUE TITLE
About Intel Platform Trust Technology

### ISSUE THREAD

**Issue by mdogwoop** [gabrielcasag/EFI-IDEAPAD-i5-8250U-330-15IKB-OPENCORE#2]
I can't find the Intel Platform Trust Technology switch in the bios. What is the bios version you are using? In which country was your device purchased? It seems that the China version of the device hides this switch

**Comment by gabrielcasag** [comment]
hi @mdogwoop 

my model is the 81FE0001BR, bought on Brazil

i tried to boot with this enable seems to work fine, you have tried to boot with the EFI?

**Comment by mdogwoop** [comment]
thank you
