### ISSUE TITLE
The HDMI crashes unplug it,  But after sleep works perfect.

### ISSUE THREAD

**Issue by andrewvideo** [gabrielcasag/EFI-IDEAPAD-i5-8250U-330-15IKB-OPENCORE#20]
The HDMI works great but the problem it's crashes when you unplug it.  Laptop screen goes blank.  But if you put the laptop to sleep first then wake it up.  The HDMI works perfect. 

Thank you for your hardworkd

**Comment by gabrielcasag** [comment]
hey @andrewvideo!

i suggest you to take a look at [this](https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/connector.html) section of the guide, maybe have some differences with the igpu part
