### ISSUE TITLE
About Ideapad 330 15IKBR i7-8550U

### ISSUE THREAD

**Issue by alvesitalo** [gabrielcasag/EFI-IDEAPAD-i5-8250U-330-15IKB-OPENCORE#23]
Hey, thanks for making your EFI folder available.
I have a question about ideapad 330 with intel i7 and full hd screen, which kexts/settings do I need to change? 
I tested with your settings on ventura but it didn't even boot.

**Comment by gabrielcasag** [comment]
Hi @alvesitalo!

Probably the problem you might be facing is related to the difference in iGPU. I recently upgraded with a full hd display as well, so this works without changes.


So, when you tried to boot, was it using a USB stick with the recovery image? And it didn't even give a boot image or boot picker?

If yes, I suggest you try booting with the _-igfxvesa_ flag added to boot-args in your config.plist

**Comment by alvesitalo** [comment]
It worked, thanks!

**Comment by gabrielcasag** [comment]
hi @alvesitalo 

this will works butt will deactivate your gpu acceleration, which can cause slowless on the use of the OS.

but it also means that have a problem with the iGPU patchs, i suggest this links to fix that in your EFI:

- https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html#deviceproperties
- https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/#intel-igpu-patching
