### ISSUE TITLE
THANK YOU!!!

### ISSUE THREAD

**Issue by firofame** [gabrielcasag/EFI-IDEAPAD-i5-8250U-330-15IKB-OPENCORE#28]
Your EFI works perfectly for my device Avita Liber Core i5 8th Gen 8250U - [NS14A2IN206P](https://www.flipkart.com/avita-liber-core-i5-8th-gen-8-gb-256-gb-ssd-windows-10-home-ns14a2in206p-thin-light-laptop/p/itmfg9zvdehyvh7e)

**Comment by firofame** [comment]
The trackpad isn't working. but I can't complain because I use the mouse most of the time and it works perfectly.

**Comment by gabrielcasag** [comment]
Hi @firofame, awesome news that worked too!

For your trackpad, try to replace the file in Kexts/Voodooi2c.kext for other like Voodooi2chid.kext or VoodooRMI.kext (you also need to adjust your config.plist)

Here some links:
- https://dortania.github.io/OpenCore-Install-Guide/ktext.html#laptop-input
- https://dortania.github.io/Getting-Started-With-ACPI/Laptops/trackpad-methods/manual.html#create-osys-variable-under-i2c-scope
